version: '3'

services:
  honeybadger-test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/local/src/HoneyBadgerBFT
    command: python /usr/local/src/HoneyBadgerBFT/mytest/test_honeybadger.py
